security:
  # Password hashing configuration
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
   
  # Firewall configuration
  firewalls:
  # Disable security for dev tools and assets
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
   
   # Main authentication firewall
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      user_checker: App\Security\UserChecker

      logout:
        path: app_logout
        target: app_login

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800     # 7 days
        path: /
        always_remember_me: false

 # Add access rules later for admin/editor roles
  access_control: []
    

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10

