# config/services.yaml
parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Force Symfony to use the classic CSRF token manager
    security.csrf.token_manager.inner:
        class: Symfony\Component\Security\Csrf\CsrfTokenManager
        arguments:
            $generator: '@security.csrf.token_generator'
            $storage: '@security.csrf.token_storage'

    # Proper way to override the alias
    security.csrf.token_manager:
        alias: security.csrf.token_manager.inner
        public: true

